### ISSUE TITLE
Looking for better source for the sbs group channels

### ISSUE THREAD

**Issue by hikavdh** [tvgrabbers/tvgrabnlpy#22]
Still looking for a source containing better (with season/episode) information for the sbs group channels (sbs6, net5, veronica and sbs9)

**Comment by SirJohnDoe** [comment]
Just use the horizon.tv api for all Dutch channels so you can ditch a couple other sources. It provides episode names and numbers.

Have a look at horepg for some inspiration: https://github.com/beralt/horepg

**Comment by hikavdh** [comment]
I'll have a look. Previously horizon seemed not to be to reliable, but if that changed!

**Comment by hikavdh** [comment]
I took a quick look and since it's json it's easily implementable. AND it's basically only two grabs! It will though go into the 22 branch which at present is still in Alfa. It has an opener structure for adding sources.
Hika

**Comment by hikavdh** [comment]
There is a first [test version 2.2.0](https://github.com/tvgrabbers/tvgrabnlpy/releases/tag/alfa-2.2.0-p20150817) available with the Horizon source. Unfortunately they only have episode names and numbers and no season number. I'm thinking  about adding a ttvdb lookup.
Hika
