### ISSUE TITLE
Fox only shows Garage Gold

### ISSUE THREAD

**Issue by BlackBurn83** [tvgrabbers/tvgrabnlpy#28]
Fox only shows Garage Gold as show instead of all the shows that there are on.
I already tried to remove all the files and did a complete re-run which seemed to work, I saw multiple shows, but unfortunately after a few days this went away and only Garage Gold is displayed.

I'm running the latest stable 2.1.5, please let me know if I can upload any files that can be helpful.

**Comment by hikavdh** [comment]
Have you checked out the latest issues https://github.com/tvgrabbers/tvgrabnlpy/wiki/actueel and tried 2.1.6-beta? 

Hika

**Comment by BlackBurn83** [comment]
Installed version 2.1.6-beta, deleted all files and so far, everything seems collected right.
I will keep an eye on it for a couple of days.
