### ISSUE TITLE
Unable to fetch from teveblad.be

### ISSUE THREAD

**Issue by wytsekamsma** [tvgrabbers/tvgrabnlpy#41]
Seems something changed on their website during the last week (I first installed tv_grab_nl_py last week), they're now referring to HLN (http://www.hln.be/hln/nl/929/Kanaal-TV/index.dhtml#aanbod). The links it is trying (http://www.teveblad.be/tv-gids/zenders et cetera) indeed give a 404, so I guess this is a quite fundamental change, which may or may not be related to the acquisition of teveblad.be by De Persgroep (see here: http://www.persgroep.be/nl/news/overdracht-van-titels-sanoma-naar-de-persgroep-goedgekeurd). 

Of course it would be nice to have this fixed (if at all possible), but more importantly... I think it would be useful to have the ability to disable certain sources (--disable-teveblad, --disable-tvgidstv et cetera), in case of such eventualities? Or maybe there is some setting I overlooked. In any case... now it seems to just get stuck with this...

    http://www.teveblad.be/tv-gids/2015-09-08/zenders/bbc2-nl
    [repeats for each channel]
    Cannot open url http://www.teveblad.be/tv-gids/zenders/: Not Found
    teveblad channel info file: /home/tvheadend/teveblad_channels.html not found

**update**
I decided to see if copying in the 'teveblad channel info file' would help (even though it says it is not necessary anymore?). It seems to have stopped the script from getting stuck. Still, maybe it would be good to look into the above :)

**Comment by hikavdh** [comment]
Thanks. I see it and the new page is fundamentally different. I have to reexamine and rewrite that source. In the present 2.1 branch the only way to disable the source is by removing the TeVeblad.ID's from the channel lines in your config. Changing  
`NPO 1;1;1;nederland-1;;npo-1;1;2;1165799/npo-1.jpg`
to
`NPO 1;1;1;nederland-1;;;1;2;1165799/npo-1.jpg`  

You can also try the new 2.2 branch, that has a disable-source option. But it is still in alfa.

**Comment by hikavdh** [comment]
I'll push a small update later tonight with the teveblad.be source disabled!

**Comment by hikavdh** [comment]
OK, here https://github.com/tvgrabbers/tvgrabnlpy/releases/tag/stable-2.1.12 you'll find a version with teveblad.be disabled. Somewhere in the near future I'll publish a rewrite of the teveblad source.

**Comment by wytsekamsma** [comment]
Perfect. I was considering removing the ID's, but that seemed to me like killing a fly with a cannon. I'll update to 2.1.12 and/or maybe try 2.2 for a while. Thanks for your quick response.

**Comment by hikavdh** [comment]
This is going to be tricky or even impossible for now. It's a flash app and I'm not sure I can find and/or access the source.

**Comment by hikavdh** [comment]
I did a fast search for alternate Flemish sources and found: 
http://www.zita.be/entertainment/tv-gids/  
http://www.nieuwsblad.be/tv-gids

I'll look at it tomorrow.

**Comment by samalloing** [comment]
How about Humo TV Guide? They have JSON: http://www.humo.be/api/epg/humosite/schedule/main/2015-09-02/full. http://www.humo.be/tv-gids/

**Comment by hikavdh** [comment]
Thanks! I'll look at it.

**Comment by hikavdh** [comment]
Looks promising! Do you know more syntax then:
http://www.humo.be/api/epg/humosite/channels
http://www.humo.be/api/epg/humosite/schedule/main/2015-09-02/full
http://www.humo.be/api/epg/humosite/schedule/rest/2015-09-02/full
Can I do a channel selection or multiple days?
The channels have an id and a code, what then do I use?
`{"id":7,"code":"EEN","display_name":"\u00e9\u00e9n",`

**Comment by samalloing** [comment]
I don't think you can select more days at once. It's day by day. You can use both. They are used both. You can also use the display name depending on what you want to do.

I also found somebody who wrote a parser: https://github.com/francisdb/belgiantv/blob/master/app/services/HumoReader.scala

He also has parser for two other belgian tv guides. But these also seem day by day: 
* Yelo: https://github.com/francisdb/belgiantv/blob/master/app/services/YeloReader.scala
* Belgacom/proximus: https://github.com/francisdb/belgiantv/blob/master/app/services/BelgacomReader.scala

**Comment by hikavdh** [comment]
Thanks again. It seems you can either select one of the two groups or one single channel, and then only by id. And if you leave out full, you only get title and start/end times. I'll finish this one and the full integrations of ttvdb and then bring 2.2 to beta. I'll look into other sources after. So probably this weekend or early next week.

**Comment by hikavdh** [comment]
A first setup with the Humo source can be found at https://github.com/tvgrabbers/tvgrabnlpy/releases/tag/alfa-2.2.0-p20150904

**Comment by hikavdh** [comment]
The first beta is out! With the humo.be source and integrated theTVDB.com support!
https://github.com/tvgrabbers/tvgrabnlpy/releases/tag/beta-2.2.0-p20150907
