### ISSUE TITLE
Error with new nieuwsblad.be source

### ISSUE THREAD

**Issue by kyl416** [tvgrabbers/tvgrabnlpy#48]
I get the following when I try to run configure after you added the nieuwsblad.be source

```
Traceback (most recent call last):
  File "tv_grab_nl.py", line 11516, in get_channels
    strdata = self.get_page(self.get_url('base'))
  File "tv_grab_nl.py", line 11494, in get_url
    locale.setlocale(locale.LC_TIME, ('nl_NL', 'utf-8'))
  File "/usr/lib/python2.7/locale.py", line 579, in setlocale
    return _setlocale(category, locale)
Error: unsupported locale setting
```

**Comment by hikavdh** [comment]
LC_TIME is a subset of LC_ALL and I didn't want to change more then needed.  If you ask `print locale.getlocale(locale.LC_TIME)` You get that one else you get ALL

**Comment by hikavdh** [comment]
I've set it back to beta. I might have to set up an Ubuntu system to test. At present I do not understand. Except possibly that you simply do not have the Dutch locale definition on your system. But as far as I know those are always present on Linux, only possibly not under Windows. I might have to create my own weekdaynumber to weekday table.

**Comment by hikavdh** [comment]
What do you get on `locale.setlocale(locale.LC_TIME, ('nl_NL', 'UTF-8'))`?

**Comment by hikavdh** [comment]
Oh if you want to get out of the Python interpreter you press Ctrl-D

**Comment by kyl416** [comment]
It looks like at least Ubuntu only activates your own locales, here's the output of locale -a
```
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX
```
And this was the output:
```
locale.setlocale(locale.LC_TIME, ('nl_NL', 'UTF-8'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/locale.py", line 579, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```
After I manually use the locale-gen command to add nl_NL, nl_NL.utf8, nl_BE and nl_BE.utf8 they showed up on the list:
```
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
nl_BE
nl_BE.iso88591
nl_BE.utf8
nl_NL
nl_NL.iso88591
nl_NL.utf8
POSIX
```
And now the command works:
```
locale.setlocale(locale.LC_TIME, ('nl_NL', 'UTF-8'))
'nl_NL.UTF-8'
````

**Comment by hikavdh** [comment]
So I guess I create a lookup table for those weekdays

**Comment by kyl416** [comment]
Yeah, I'm not sure how other Linux distributions behave when it comes to the default set of locales

**Comment by hikavdh** [comment]
Nah, my assumption was mistaken, the tables are there by default but as you pointed out, you need to generate the locale out of it. I forgot.

**Comment by hikavdh** [comment]
And in Windows you have to download them. I think

**Comment by hikavdh** [comment]
Ok try again. It should now work properly

**Comment by winfried** [comment]
On 11/16/2015 10:07 PM, Hika van den Hoven wrote:

Hi,

> But as far as I know those are always present on Linux, only possibly
> not under Windows. I might have to create my own weekdaynumber to
> weekday table.

On Debian/Ubuntu bases systems (and AFAIK on all Linux systems) you are
asked what default locale you want to have when installing the system
and what additional locales you want to have. Changing it later or
adding locales is perfectly possible:
https://help.ubuntu.com/community/Locale
https://people.debian.org/~schultmc/locales.html

Winfried

**Comment by hikavdh** [comment]
I should have known, I just didn't realize at the moment.
