### ISSUE TITLE
TypeError when creating config file

### ISSUE THREAD

**Issue by jowandijkhuis** [tvgrabbers/tvgrabnlpy#54]
I was setting up tvgrabnlpy on my Synology. After running the command "tv_grab_nl.py --configure" 
the file tv_grab_nl_py.conf isn't created due to a TypeError. How can I fix this?
![tvgrab](https://cloud.githubusercontent.com/assets/593324/12313338/dfeeae8e-ba66-11e5-9d77-fb877e6cd731.jpg)

**Comment by hikavdh** [comment]
It failed to grab the channel info from npo.nl. It's not because it's not available, so try again as it says in a few minutes. If it persists, you can try adding `--disable-source 4`. This way the npo.nl source is disabled, so it should complete. Only without channel info from npo.nl

**Comment by jowandijkhuis** [comment]
Yes that did it! Thanks for the help (and quick response). Actually the solution was right in front of me. But didn't know the code for disabling a failing source.

**Comment by hikavdh** [comment]
`tv_grab_nl_py --help`
