### ISSUE TITLE
Unable to run recent versions of the grabber on Ubuntu 12.04

### ISSUE THREAD

**Issue by JanCeuleers** [tvgrabbers/tvgrabnlpy#55]
The version of Python 2.7 that comes with Ubuntu 12.04 is 2.7.6, which is older than the 2.7.9 version that is now the minimum.
I have installed Python 3 from the Ubuntu repository (which is version 3.2), and if I run the grabber using it, the following error occurs:
  File "tv_grab_nl_py.github/tv_grab_nl.py", line 362
    self.patchdate = u'20160116'
                               ^
SyntaxError: invalid syntax

Which is weird; why wouldn't a recent Python know about Unicode string literals? (Note that in a non-proportional font the arrow points at the closing single quote).

**Comment by hikavdh** [comment]
It's a weird error I can not explain. But the program is only very limited and already some time ago tested with Python 3. You forget the other message you got "tv_grab_nl_py does not yet support Pyton 3 or higher. Expect errors while we proceed", Also 3.2 is really old!
I suggest installing Python 2.7.9 or 2.7.10. Especially 2.7.9 is in large part backported functionality from the Python 3  branch.

**Comment by hikavdh** [comment]
I did a quick test with Python 3 and there are several for that branch syntax errors!

**Comment by JanCeuleers** [comment]
I installed Python 2.7.11 in /usr/local/bin (i.e. keeping the stock version untouched) in order to avoid any fallout, and the grabber does indeed work fine now.
As you can tell I'm weary of fallout; there is a reason why I'm on Ubuntu 12.04 LTS. I will migrate to 16.04 when its first point release is out and want to use the stock versions of everything to the extent possible.
Anyway thanks for your reply; I think I'm good with this workaround for now.
