### ISSUE TITLE
Bug on NPO dates

### ISSUE THREAD

**Issue by kyl416** [tvgrabbers/tvgrabnlpy#58]
I think there's a bug on the NPO dates from the latest update. I'm getting data starting with January instead of February.

This is an example of what my log shows for NPO 1's merg statistics:
```
2016-02-25 15:26:38 : Merg statistics for NPO 1 (channel 92 of 97) from vpro.nl into npo.nl
2016-02-25 15:26:38 :    327 programs in npo.nl      for range: 25-Jan 06:00 - 03-Feb 06:10, 
2016-02-25 15:26:38 :    220 programs in vpro.nl     for range: 25-Feb 06:10 - 01-Mar 05:59
```

**Comment by hikavdh** [comment]
I saw it this morning and has nothing to do with the update. It is just coincidence that March is the first month since the source was created that has a different three letter short for the month in English and in Dutch. I fixed it this morning at noon and re-posted the version. So download again

**Comment by hikavdh** [comment]
Oops, I let the replacement month number start with 0. So it is just cosmetic.

**Comment by hikavdh** [comment]
I saw the npo issue on the difference between mrt and mar this morning so I thought to fix it fast and pull it in with the release, but I was in a hurry as I had to go. I just added a dummy month as item 0 so it is OK now.
The three letter shorts are only different for March, May and October and I created the source in November and mistook the language used.
