### ISSUE TITLE
Error on latest commit

### ISSUE THREAD

**Issue by kyl416** [tvgrabbers/tvgrabnlpy#59]
Looks like there's a typo on the latest commit:

```
Traceback (most recent call last):
  File "tv_grab_nl.py", line 3784, in <module>
    config = Configure()
  File "tv_grab_nl.py", line 364, in __init__
    self.beta = Beta
NameError: global name 'Beta' is not defined
```

It should say:
```
self.beta = True
```

**Comment by hikavdh** [comment]
Stupid! I did that after testing. I'm a bit sick so not so alert! ;-( Thanks!

**Comment by kyl416** [comment]
Can you take another look at the code for grabbing the channel list from oorboekje.nl? I just reran configure and all the stations vanished

**Comment by hikavdh** [comment]
Weird! I did not actually test a channelscan, but the message on a grab that all channels disappeared had gone and I corrected the same there, I thought!? But I however now see that the group assignment might fail for the regional channels. It's the trouble with that I had to do this page through regexes. One changed comma...
In version 3 I do not use regexes anymore. It's all much more sturdy! 
I'll look deeper into it. I now do recall that that check, resulting in a mail on missing channels does not use the same code as a channelscan!

**Comment by kyl416** [comment]
I lost all channels from them, the remaining radio stations just list the VPRO and NPO sources in my configure:
```
Classic FM;11;7-classic_fm;;;;;;;;classic_fm;;;;;;4;radio_classicfm.png
NPO 3FM;11;4-294;;;;;294;;;3fm;;;;;;7;radio_channel/294/logo/regular_logo3fm.png
```

**Comment by hikavdh** [comment]
And you do not get an error about a failed source? Because it then would refuse to update the config.
And nothing in the log? It might be an original logical error, that pops up because of the change.

**Comment by hikavdh** [comment]
OK I had to step back into my original thinking. I did not follow my own code anymore. It is the same slash as in the other case. Change line 12938 from:
```
                if not '"stream.php?zender=' in ch:
```
to
```
                if not '"/stream.php?zender=' in ch:
```
I'll push an update later.
