### ISSUE TITLE
TVHeadend

### ISSUE THREAD

**Issue by antoniong** [tvgrabbers/tvgrabnlpy#63]
Ik genereer periodiek een XML file en die werkt prima binnen EyeTV. Ik krijg het echter niet voor elkaar dezelfde XML file binnen TVHeadend te plaatsen.

Waar kan ik die ergens neerzetten binnen de TVHeadend folder?

**Comment by hikavdh** [comment]
Ik moet je naar het tvheadend forum door verwijzen. Ik werk zelf met mythtv
