### ISSUE TITLE
"Unexpected error in RTL Z thread"

### ISSUE THREAD

**Issue by antoniong** [tvgrabbers/tvgrabnlpy#66]
Since today. No idea what is wrong. Logs enclosed.

[Archief.zip](https://github.com/tvgrabbers/tvgrabnlpy/files/380191/Archief.zip)

**Comment by hikavdh** [comment]
It loos like an unexpected side effect of disabling tvgids.tv. I have to look deeper

**Comment by hikavdh** [comment]
I have reenabled it again. So you will see all those failures again on tvgids.tv. I will look why this now does not work properly, while it did in the past.

**Comment by hikavdh** [comment]
See https://github.com/tvgrabbers/tvgrabnlpy/releases/tag/beta-2.2.15-p20160725
