### ISSUE TITLE
RTL program names being replaced

### ISSUE THREAD

**Issue by kyl416** [tvgrabbers/tvgrabnlpy#67]
Is there anyway to prevent the program names from other sources like VPRO, horizon and tvgids.nl replacing the names provided by RTL?

For RTL's teleshopping blocks they have more specific names like "Teleshop 4: Dit Is Mijn Toekomst" and ""Teleshop 4: Thane" while  horizon, tvgids.nl and VPRO just use "Teleshop" or "Teleshop 4" for all of them, so there's no way to tell the difference between a live psychic call in show or if it's Sully selling a mop. I managed to get some of them to stay with the notitlesplit, but some are still being replaced by the generic "Teleshop" and "Teleshop 4" names.

It also extends to other shows:
"RTL Late Night"  just shows up as "Late Night"
"RTL Boulevard" just shows up as "Boulevard"
"RTL Nieuws" just shows up as "Nieuws"
"RTL Weer" just shows up as "Weer"

**Comment by hikavdh** [comment]
Yes there are, but first I have to understand, what is happening. Isn't rtl.nl prime_source for all RTL channels, because the prime_source provides in essence the programme title?

**Comment by hikavdh** [comment]
Also RTL is one of the most stable providers of episode titles. Aren't they in there?
I did a quick check. I do some renaming in the merge module to cover source differences, but that is mostly for the Dutch, Flemish, English and German public channels. I never extended it further. I only see a rename for the 4 RTL channels on horizon from RTL nieuws to nieuws. This to me implies that RTL itself names it just Nieuws!

**Comment by hikavdh** [comment]
I did a test-run.
- Your teleshop things are in the episode title. That's where rtl itself puts it.
- Late Night, Boulevard and Weer show up as "RTL Late Night, "RTL Boulevard and "RTL Weer. 
- Somehow the name change on nieuws when merging with horizon becomes dominant. I don't remember why I put it there. I remove that line when I put 2.2.17 stable.

**Comment by kyl416** [comment]
This is what is in the RTL feed
```
{
    "abstract_key": "132237",
    "abstract_title": "RTL Nieuws",
    "season_key": "351987",
    "episode_key": "352223",
    "station": "RTL4",
    "rerun": false,
    "unixtime": 1471987920
},
```
```
{
    "abstract_key": "367872",
    "abstract_title": "RTL Late Night: Olympic Edition",
    "season_key": "367873",
    "episode_key": "367874",
    "station": "RTL4",
    "rerun": false,
    "unixtime": 1471992540
},
```


But for some reason this is the final output on the xmltv file I grabbed about 2 hours ago for those timeslots:
```
  <programme start="20160823213200 +0000" stop="20160823215100 +0000" channel="4.tvgids.nl">
    <title lang="nl">Nieuws</title>
    <sub-title lang="nl">Laat</sub-title>
  </programme>
```
```
  <programme start="20160823224900 +0000" stop="20160823234600 +0000" channel="4.tvgids.nl">
    <title lang="nl">Late night</title>
    <sub-title lang="nl">Olympic Edition</sub-title>
</programme>
```

**Comment by hikavdh** [comment]
Oh, and one other thing. In version 3 I moved that to the grabber file and only left these. It is needed for the merging that the names on all sources are the same, that's why this is in place:
```
	"channelprogram_rename":{
		"0-1":{"journaal":"NOS Journaal", 
			"nieuws":"NOS Journaal", 
			"tekst-tv":"Tekst TV", 
			"nos tekst tv":"Tekst TV", 
			"nos tekst-tv":"Tekst TV"},
		"0-2":{"journaal":"NOS Journaal", 
			"nieuws":"NOS Journaal", 
			"tekst-tv":"Tekst TV", 
			"nos tekst tv":"Tekst TV", 
			"nos tekst-tv":"Tekst TV"},
		"0-3":{"journaal":"NOS op 3", 
			"nieuws":"NOS op 3", 
			"tekst-tv":"Tekst TV", 
			"nos tekst tv":"Tekst TV", 
			"nos tekst-tv":"Tekst TV"},
		"0-5":{"herhalingen":"Journaallus"},
		"0-6":{"herhalingen":"Canvaslus"},
		"0-7":{"nieuws":"BBC News", 
			"het weer":"Regional News and Weather"},
		"0-8":{"nieuws":"BBC News", 
			"het weer":"Regional News and Weather"},
		"0-9":{"nieuws":"Tagesschau"},
		"0-10":{"nieuws":"Heute"}
		},
```

**Comment by kyl416** [comment]
Yeah I found the rename code for version 2, it has the Nieuws thing:
```
            if self.source == 'horizon.tv':
...
                if chanid in ('0-4', '0-31', '0-46', '0-92'):
                    if 'rtl nieuws' in mname:
                        return 'Nieuws'
```

**Comment by hikavdh** [comment]
To me it looks like your rtl.nl fetch fails. Could it be, that it has geo blocking?
```
  <programme start="20160824004900 +0200" stop="20160824014600 +0200" channel="4">
    <title lang="nl">RTL Late Night</title>
    <sub-title lang="nl">Olympic Edition</sub-title>
    <desc lang="nl">Speciale uitzending vanuit de RAI in Amsterdam. Humberto Tan ontvangt veel van de net uit Rio teruggekeerde sporters. De meest opvallende verhalen van de Olympische helden komen aan bod.</desc>
    <category>Talk</category>
    <episode-num system="xmltv_ns">0 . 0 . </episode-num>
  </programme>
  <programme start="20160824014600 +0200" stop="20160824021600 +0200" channel="4">
    <title lang="nl">Teleshop 4</title>
    <sub-title lang="nl">Dit is mijn toekomst</sub-title>
    <desc lang="nl">shoppen: Homeshoppingprogramma.</desc>
    <category>Educational</category>
    <rating system="kijkwijzer">
      <value>16+: ST</value>
    </rating>
  </programme>
  <programme start="20160824234900 +0200" stop="20160825004300 +0200" channel="4">
    <title lang="nl">RTL Boulevard</title>
    <sub-title lang="nl">Aflevering 169</sub-title>
    <desc lang="nl">Amusement.: Amusement. Dagelijkse mix van actualiteiten, vermaak en opinies met één of twee deskundigen, gasten of andere nieuwsmakers. In hoog tempo volgen afwisselende items en reportages elkaar op met de thema's showbizz, crime, royalty en lifestyle. Seizoen 18.</desc>
    <category>Talk</category>
    <episode-num system="xmltv_ns">17 . 168 . </episode-num>
    <rating system="kijkwijzer">
      <value>AL: T</value>
    </rating>
  </programme>
```

**Comment by hikavdh** [comment]
Check the fetched-programs file on what every source contributes

**Comment by kyl416** [comment]
I just copied the title and sub-title so it's easier to see here. The actual xmltv file has all those additional details.

There are no failures from rtl.nl in the log
