### ISSUE TITLE
tvheadend support script

### ISSUE THREAD

**Issue by egraaf** [tvgrabbers/tvgrabnlpy#70]
I use Tvheadend with the small tvheadend support script in tvgrabnlpy/tvheadend

Tvheadend will call the support script with the --capabilities option, but Tvheadend will not use tvgrabnlpy as an EPG grabber due to this line:

`[ $? == 0 -a -f $XML_OUT ] &&  cat $XML_OUT`

Because $XML_OUT has not been generated the -f will exit with status 1 and this causes Tvheadend to reject tvgrabnlpy as an EPG grabber (it will not show up in the dropbox with selectable EPG grabbers).

I added an exit  0 statement at the end of the support script, and now Tvheadend will use the script.

**Comment by hikavdh** [comment]
Very probably it will nowadays also work without the small script, as I made when working on 2.2.0 a better distinction between what went to stdout an to stderr. I don't use tvheadend so I have not actually tested it.

**Comment by egraaf** [comment]
Thank you very much.

I have taken the small script out now, and am using tvgrabnlpy directly from Tvheadend now. I believe it is working fine. Tvheadend is using the Python script directly, and I see EPG data in Tvheadend.

Closing the issue.
