### ISSUE TITLE
Remove groupname list, regardless of separation character

### ISSUE THREAD

**Issue by pensionado** [tvgrabbers/tvgrabnlpy#72]
Please enhance remove group name list by not only checking for : but also for , Channels have programs like 'Veteranen van 7, The expendables' which results in the title 'Veteranen van 7' although I added it as a group name list to be removed, so suspect you only check for : and not , as group name separation.

**Comment by hikavdh** [comment]
I have to think about that. First it is the same code that does the title split to extract potential episode titles and secondly because you do not want it to act uncontrolled. A comma is a not uncommon belonging part of any title.

**Comment by pensionado** [comment]
True, but then if you found a comma you could then check if what is in front is a group name list to be removed ?

**Comment by pensionado** [comment]
Having done some research after inserting following lines:
`        if ptitle.lower() in config.groupnameremove:
			ptitle=psubtitle
			psubtitle=''
`
After the part where you remove the groupname in check_title_name, it worked like I wanted. Maybe an enhancement for next release ?

**Comment by hikavdh** [comment]
It is completely unclear what you mean. Give me a diff. And use triple back quotes to mark multiple lines as code, like:
```
line 1
line 2
    line 3 with indentation.
```

**Comment by pensionado** [comment]
Here is the diff:
> diff Documents/tv_grab_nl.py Data/Computer/tv_grab_nl.py 
6603a6604,6606
>         if ptitle.lower() in config.groupnameremove:
>                       ptitle=psubtitle
>                       psubtitle=''

**Comment by pensionado** [comment]
Sorry but this github editing destroys all the formatting. using insert quotes and code does not prevent it from removing spaces, cr/lf and other formatting.

**Comment by hikavdh** [comment]
As I said enclose in triple backquotes on leading and following lines (the one left-top next to the `1` key). It's not default HTML but markdown. And give line numbers and context where to insert, marking new/removed lines with a leading +/-

**Comment by hikavdh** [comment]
If 6606 is your starting line you mean: ?
```
                    ptitle = "".join(p[1:]).strip()

        # Fixing subtitle both named and added to the title
+        if ptitle.lower() in config.groupnameremove:
+            ptitle=psubtitle
+            psubtitle=''
+
        if ptitle.lower() == psubtitle.lower() and program['genre'] != 'serie/soap':
            psubtitle = ''
```

**Comment by pensionado** [comment]
Correct, but I inserted the code before the comment, so it falls under the comment of removing groupname list, because that is what it actually does, for group names that didn't use the : delimiter

**Comment by hikavdh** [comment]
Well that is very dangerous as it will replace the program name with the episode title if it is present in the groupnameremove list regardless of anything. Like whether there is any episode title at all. Also you said it was comma separated in your case, so they cannot already be split as that only happens on a colon??

**Comment by pensionado** [comment]
From what I found is that programs often have the format of _groupname : actual name_ And then the code in front of where I did the insert will remove the groupname part. But if they used  this format _groupname ,  actual name_ then the generic code which separates series name from episode name will put the groupname in the title and the actual name in the subtitle. So what the inserted code does is check if the whole title is in the list of groupnames and if so, he will replace it with the subtitle, which really is the actual film title. Cant see any danger with that because the code checks if the complete title is in the list of groupnames to be removed..

**Comment by hikavdh** [comment]
True in part. That's Horizon.tv They for instance for the news give "Journaal" as Name and "Journaal, 20:00 uur" as episode title. I have been breaking my mind for a long time on how to properly handle that. It's what "# And the other way around" checks. It any how is quit complex, especially not to target to wide! There simply is to much possible variation.
