### ISSUE TITLE
Normal run 40 min. now suddenly >440 minutes.

### ISSUE THREAD

**Issue by antoniong** [tvgrabbers/tvgrabnlpy#73]
Normally a run takes 40 min. Now all of a sudden running time is over 11-fold. Result contains numerous "internal server errors". Might be the cause.

Is this error message caused/related by TVgabnlpy or is this from the site where the info is grabbed from?

I have been "cleaning" out my Mac. So it could be used with something I did (but what?). So I dl'ed the latest .zip, did a config but result remains same. Long running time & error messages.

**Comment by hikavdh** [comment]
It probably is caused by the sources especially tvgids.tv and in lesser degree nieuwsblad.be have been having problems since this summer. But send me a log and configuration. I haven't seen it!

**Comment by hikavdh** [comment]
Or lets be correct "internal server error" comes from the urllib module. It is possible that you broke one of its dependencies :-(

**Comment by antoniong** [comment]
This morning it ran without any errors and within the regular time. So solved by itself. No idea why.
