### ISSUE TITLE
#76 if not(!) finished.

### ISSUE THREAD

**Issue by TonVH** [tvgrabbers/tvgrabnlpy#77]
I have asked earlier but have not gotten a (clear) answer.

You talk about version 3 but what version 3 do you mean. There are 3 possibilities:
1. 3 as in tvgrabbernl (this site).
2. 3 as in tvgrabnl3 (site tvgrabpyApi.
3. 3 as in Python 3.x.

**Comment by hikavdh** [comment]
Number 2. It is the successor of this program. The API is version 1 but the Dutch/Flemish front end started with version 3

**Comment by antoniong** [comment]
Sorry but you are only making the confusion larger and larger by answering questionnaires not asked. Try to understanding the problem from viewpoint of a simpel Usher and not developer.

So let'S go back to the beginning.

Which tvgrabnl  should I use being the latest and most futureproof?

Verstuurd vanaf mijn iPad

**Comment by hikavdh** [comment]
tv_grab_nl.py will in the near future no longer be supported. The successor is tv_grab_nl3.py as part of tvgrabpyAPi
