### ISSUE TITLE
Add 'showicon' to EPG details?

### ISSUE THREAD

**Issue by wbmk78** [tvgrabbers/tvgrabnlpy#78]
It would be a nice addition to the EPG when a showicon URL with a movie poster or something is added. The horizon.tv guide/site has these icon's for allmost every entry..

**Comment by hikavdh** [comment]
I'll take it under advise for the future graphical frontend for tvgrabpyAPI. tvgrabnlpy 2.2 won't be developed any further and wiyhout some graphical frontend ... !
