### ISSUE TITLE
Onderstreuning voor DVB Link

### ISSUE THREAD

**Issue by alex341** [tvgrabbers/tvgrabnlpy#81]
DVB Link is een vergelijkbaar platform als MythTV en TVHeadend. Echter, het mist een goede grabber. Wat zou het fantastisch zijn als tv_grab_nl_py zou kunnen draaien op een Synology NAS, waar DVBLink op draait.

**Comment by hikavdh** [comment]
Versie 2 wordt nog maar beperkt ondersteund. Probeer [versie 3](https://github.com/tvgrabbers/tvgrabpyAPI)

**Comment by dunron** [comment]
Op onze Synology NAS draait tv_grab_nl_py al jaren om DVBLink te voorzien van EPG-data. Werkt fantastisch inderdaad. Hulde aan Hika!

**Comment by alex341** [comment]
Da's goed te horen. Ik ben slechts een beetje thuis in Linux. Kun je me aangeven hoe je dat hebt gedaan?

**Comment by dunron** [comment]
Python Module installeren in DSM en volgens de aanwijzingen het tv_grab_nl_py script op de commandline (ssh). Het tv_grab_nl_py script run je via Task Scheduler, ik doe dat 2x daags. De output zet je in de DVBLink/xmltv directory. in DVBLink voeg je dat dan als XMLTV source toe. Als extraatje stuur ik mezelf ook nog de laatste regels van de tv_grab_nl_py log-file. Die haal ik daar uit met dit sed-commando:

`sed -n '/.*Execution complete.$/ { :a; n; p; ba; }' $HOME/.xmltv/tv_grab_nl_py.log`

Succes!

**Comment by alex341** [comment]
Tnx voor de input. Echter, ik zit met wat probleempjes. (ook met Hilke daar mee bezig...).
Ik heb Python geinstalleerd in de DSM en vervolgens, middels Putty als admin de (nieuwere) tvgrappyAPI en de benodigde software geinstalleerd. 
Echter, als ik de --configure commando geef, krijg ik geen .conf file. Blijkt een probleempje te zijn met het runnen van tv_grab_nl3_py als admin.
Bovendien, ik heb op mijn Synology (een DS214+) geen /HOME directory, noch de mogelijkheid om er een te creeren. (ook als admin doet ie het om een of andere reden niet).
Mijn vragen aan jou: hoe heb je het config file gecreeerd? Waar zet je vervolgens de output van de grabber neer? Als je via de Task Scheduler als admin tv_grab_nl_py runt, werkt het dan (Hilke gaf aan dat het niet zou werken, als beveiliging)? En krijg je ook de programma info van NPO, aangezien dat een van de belangrijkste redenen was om tvgrabnlAPI te kiezen omdat NPO 1 onder tv_grab_nl_py niet meer zou werken?

**Comment by alex341** [comment]
Ben al weer een stukje verder; tv_grab_nl3.py haalt zijn info op en zet deze in .../admin/.xmltv/program_cache3.db. Maar hoe zet jij vervolgens de in DVBLink? In DVB Link zit onder bronnen de tab EPG Bronnen. De map voor xmltv bestanden staat standaard (bij mij) op /var/packages/DVBLinkServer/target/share/xmltv. Moet ik die nu veranderen in ...../admin/.xmltv ?
Of moet ik bij de xmltv grabber configuratie, .../admin/.xmltv als URL toevoegen?

**Comment by alex341** [comment]
Laat maar... Ben er achter!
Voor anderen met vergelijkbare problemen, zie bijlage!
[TvgrabpyAPI installeren voor DVBLink op Synology NAS.docx](https://github.com/tvgrabbers/tvgrabnlpy/files/1233731/TvgrabpyAPI.installeren.voor.DVBLink.op.Synology.NAS.docx)

**Comment by alex341** [comment]
Kan inmiddels de data handmatig in DVBLink krijgen, via Putty. Maar om het proces te automatiseren, wil ik graag weten wat je in DVBLinkServer moet instellen. Mijn grabber produceert een data file met xmltv data: /grabber/.xmltv/data.xml. 
Binnen DVBLinkServer kun je de EPG bronnen aanpassen. Standaard staat de map voor xmltv bestanden op /var/packages/DVBLinkServer/target/share/xmltv. Moet ik:
1. het data file copieren naar /var/packages/DVBLinkServer/target/share/xmltv?
2. de grabber het file rechtstreeks in de /var/packages/DVBLinkServer/target/share/xmltv laten produceren? Heb gemerkt dat als ik dat doe, nieuwe toegevoegde zenders niet naar voren komen bij het koppelen van xmltv data aan zenders. Dus dit lijkt me niet...
3. bij de URL aangeven waar het xml file staat: /grabber/.xmltv
4. bij de URL het exacte xmltv file aangeven: /grabber/.xmltv/data.xml

**Comment by dunron** [comment]
Alex, hou er rekening mee dat het een poos duurt voordat DVBLink het xmltv-bestand oppikt. Ik heb zelf de Refresh interval op 1 uur gezet. Dat is de enige controle die je lijkt krijgen van de vendor.

Optie 2. zou dus wel moeten werken.

**Comment by alex341** [comment]
Tnx!

**Comment by hikavdh** [comment]
Kunnen jullie de discussie naar de discussiegroep verplaatsen https://groups.google.com/forum/#!forum/tvgrabnlpy of https://groups.google.com/forum/#!forum/tvgrabpyapi.
Ik ga dit issue nu sluiten.

Hika
